# DEV
FROM node:18-alpine AS installer
RUN apk add --no-cache libc6-compat
RUN apk update

WORKDIR /app

RUN npm install -g turbo

COPY . .

RUN turbo prune --scope=api --docker



FROM node:18-alpine AS builder
RUN apk add --no-cache libc6-compat
RUN apk update

WORKDIR /app

RUN npm install -g pnpm

COPY --from=installer /app/out/json/ .
COPY --from=installer /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=installer /app/out/full/ .
COPY .gitignore .gitignore
COPY turbo.json turbo.json

RUN pnpm install
RUN pnpm build --filter=api...



FROM node:18-alpine AS runner

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY --from=builder ./app .

WORKDIR /app/apps/api

CMD npm run dev
