version: '3.8'
services:
  kol-web:
    image: nginx
    build:
     dockerfile: ./apps/client/Dockerfile.prod
    ports:
     - '80:80'
  kol-api:
    build:
     context: ./
     dockerfile: ./apps/server/Dockerfile.prod
    ports:
      - "5520:5520"
    restart: always
    volumes:
      - ./:/app
      - ./node_modules/eslint-config-base:/app/node_modules/eslint-config-base
      - ./node_modules/tsconfig:/app/node_modules/tsconfig
      - /app/node_modules
      - /app/apps/server/node_modules
      - /app/packages/eslint/node_modules
      - /app/packages/tsconfig/node_modules
