version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: "web"
    volumes:
     - ${PWD}/src:/web/src
    stdin_open: true
    tty: true
