services:
  - type: web
    env: docker
    name: backend
    buildFilter:
      paths:
        - ./sub/apps/server/**
    buildCommand: pnpm i && pnpm build --filter=backend
    repo: https://github.com/Angoliuk/Kings-of-loli
    dockerfilePath: ./sub/apps/server/Dockerfile.prod
    dockerContext: ./sub
    envVars:
      - fromGroup: kings-of-loli-backend
    region: frankfurt
  - type: web
    env: static
    name: web
    repo: https://github.com/Angoliuk/Kings-of-loli
    buildFilter:
      paths:
        - ./sub/apps/client/**
    buildCommand: pnpm i && pnpm build --filter=web
    staticPublishPath: ./sub/apps/client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - fromGroup: kings-of-loli-web
