services:
  - type: web
    env: docker
    name: backend
    buildFilter:
      paths:
        - apps/server/**
    buildCommand: pnpm i && pnpm build --filter=backend
    repo: https://github.com/Angoliuk/Kings-of-loli
    dockerfilePath: ./apps/server/Dockerfile.prod
    dockerContext: ./
    envVars:
      - fromGroup: kings-of-loli-backend
    plan: Free
    region: frankfurt
  - type: web
    env: docker
    name: web
    repo: https://github.com/Angoliuk/Kings-of-loli
    buildFilter:
      paths:
        - apps/client/**
    buildCommand: pnpm i && pnpm build --filter=web
    dockerfilePath: ./apps/client/Dockerfile.prod
    dockerContext: ./
    envVars:
      - fromGroup: kings-of-loli-web
    plan: Free
    region: frankfurt
